---
- hosts: all

  tasks:
    - name: deploy to server
      become: true
      git:
        repo: "https://{{ githubuser | urlencode }}:{{ githubpassword }}@github.com/zerogpm/housingExpense.git"
        dest: "/root/www/property"
        force: yes
        version: master
